name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.12"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run typecheck
        run: bun run typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.12"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run formatter
        run: bun run fmt:check
